#!/bin/sh

cd "$(dirname "$0")/.."

echo "Uninstalling mac-api..."
forever stop mac-api > /dev/null 2>&1
launchctl unload ~/Library/LaunchAgents/org.mac-api.plist
rm ~/Library/LaunchAgents/org.mac-api.plist
